export type Metadata = {
  audio?: string;
  author?: string;
  contentType?: string;
  copyright?: string;
  description?: string;
  email?: string;
  facebook?: string;
  icon?: string;
  image?: string;
  keywords?: ReadonlyArray<string>;
  language?: string;
  modified?: string;
  provider?: string;
  published?: string;
  robots?: ReadonlyArray<string>;
  section?: string;
  title?: string;
  twitter?: string;
  type?: string;
  url?: string;
  video?: string;
};
